### ISSUE TITLE
Download CSV

### ISSUE THREAD

**Issue by yotamgever** [deanshub/pivot2#12]
As a viewer, I want to export the pivot data to CSV file as I can do for any other widget , so I will be able to continue my investigation outside the Sisense environment (excel).

- [ ] Only the displayed (filtered) data is exported according to the currently selected filters.

**Comment by deanshub** [comment]
should the download csv contain the sorting information which will now be in nodejs?

**Comment by deanshub** [comment]
should not support sorting
