### ISSUE TITLE
Define page size

### ISSUE THREAD

**Issue by yotamgever** [deanshub/pivot2#17]
As a **designer**, I want to define how many rows appear in each page, so that I will be able to design my Pivot table and control the end-user experience when consuming both the Pivot data and the entire dashboard.

- [x] Number of items per page should be by default 25
- [x] Max items per page should be 1000 (currently it is 200)

**Comment by deanshub** [comment]
dependency on #3

**Comment by orelse94** [comment]
Do exports have page size definition?
