### ISSUE TITLE
Horizontal and vertical scrolling

### ISSUE THREAD

**Issue by yotamgever** [deanshub/pivot2#8]
As a **viewer**, when viewing a Pivot which is larger than its actual size in the dashboard (can't see all rows and/or columns), I want to scroll so I can see the entire data.

- [ ] Headers should be freezed when scrolling so I will have a context of the values that I'm viewing.

- [ ] Virtual scrolling should be supported

**Comment by yotamgever** [comment]
- [ ] Virtual scrolling should be supported

**Comment by deanshub** [comment]
dependency on #48
